### ISSUE TITLE
vfs-child recursive install

### ISSUE THREAD

**Issue by serkanserttop** [c9/core#107]
I wanted to test on my localhost, it used to install without a problem about a month ago.
I ran into a `ENAMETOOLONG` bug, due to the `vfs-child` module being recursively defined for some reason.

A related issue might be that I was getting a problem right after `updating plugin 55 of 57`, where it would fail to fetch the github repo. I would run the install script again, it is possible that also helped to create the error. But I ran into this installation problem every single time, and I could not install everything at one go. Therefore I cannot judge if this plays a real part, or if it is a red herring.

    Error: ENAMETOOLONG, name too long '/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/example/node_modules/vfs-child/.gitignore'
        at Error (native)
        at Object.fs.lstatSync (fs.js:796:18)
        at statter (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/nak/lib/walkdir.js:75:19)
        at readdirAction (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/nak/lib/walkdir.js:85:7)
        at /Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/nak/lib/walkdir.js:93:7
        at FSReqWrap.oncomplete (fs.js:99:15)
    '
        at EventEmitter.<anonymous> (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/plugins/c9.vfs.server/filelist.js:99:31)
        at EventEmitter.emit (events.js:110:17)
        at Parent.onExit (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/vfs-socket/consumer.js:271:17)
        at Parent.Agent._onMessage (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/smith/smith.js:471:8)
        at Transport.emit (events.js:107:17)
        at /Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/smith/smith.js:96:14
        at parse (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/smith/smith.js:252:21)
        at Socket.onData (/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/node_modules/smith/smith.js:101:9)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)

To fix it, I deleted the node_modules from the first vfs-child/examples folder.
This time I am getting the following errors.

    VFS connection does not exist
    46539: Error: ENOENT, open '/Users/serkanserttop/codespace/github.com/ajaxorg/cloud9/core/.c9/metadata/tab1'
    at Error (native)

But the app seems to work ok, it was debugging fine as well.
At least for the 3 minutes I tried.

**Comment by nightwing** [comment]
Warnings about missing metadata files are normal
The first error was caused by a symbolic link https://github.com/c9/core/tree/master/node_modules/vfs-child/example/node_modules, I will remove it. Thank you for reporting the issue.
