### ISSUE TITLE
Not able to save files I'm editing

### ISSUE THREAD

**Issue by dr3x** [c9/core#108]
Did a checkout on 6/9 and everything was working fine, then just updated to the latest today (6/25) and now I'm not able to save changes on files that I edit through the IDE.  

Commit of working version:
281925be9e8b902c08b371b5f78e192ddee57b9b (May 30th)

Nothing else on my system has changed.  

Deleted the folder and repulled, then ran install-sdk; still not saving.

Renamed core git folder to c9sdk:
node ~/source/c9sdk/server.js -p 3131 -l 0.0.0.0 -a : -w ~/source/mysource

This is my log:
Starting standalone
Connect server listening at http://<ip>:3131
CDN: version standalone initialized /home/someuser/source/c9sdk/build
Started '/home/someuser/source/c9sdk/configs/standalone' with config 'standalone'!
VFS connection does not exist

**Comment by dr3x** [comment]
**UPDATE - RESOLVED**
Just got the latest code and am unable to recreate the issue with that code so it seems o be resolved
6f8cb66296cb48f594b35aa139ed83404e42afb8

**Comment by dr3x** [comment]
Actually it is happening again, not sure what changed.  Reverting back to the commit above for now and reopening the issue.

**Comment by nightwing** [comment]
Do you see any errors in browser console?

**Comment by dr3x** [comment]
No errors. When I exit out of the page, I get prompted to save it again; click the save button but never exit.

**Comment by dr3x** [comment]
Actually I do see an error in the console log:

static/plugins/c9.ide.watcher/gui.js:105 
Uncaught TypeError: Cannot read property 'classList' of undefined

Here's the code:
            save.on("beforeSave", function(e) {
                e.document.meta.$savingValue = e.save;
                if (e.tab.classList.contains("conflict")) {
                    showChangeDialog(e.tab);
                }
            }, plugin);

**Comment by nightwing** [comment]
Could you try running install.sh from https://github.com/c9/install, it will update contents of ~/.c9 in case something  have been deleted

> I get prompted to save it again; click the save button but never exit.

does it write anything to the disk? 
try running `app.fs.writeFile("/xxx.js", ":)", console.log.bind(console))` in browser console it should create `xxx.js` file

btw which OS do you use

**Comment by dr3x** [comment]
1) Ran the install; completed, one error in log (below) but looked like the source compile success
2) Doesn't make any updates to disk.  Noticed it when I (thought it) saved and didn't see any git diffs
3) Ran the code and xxx.js file was created
4) CentOS release 6.4 (Final)

**Install log error:**
:Installing Collab Dependencies

> sqlite3@3.0.5 install /home/cloudera/.c9/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /home/cloudera/.c9/node/bin/node --eval require('/home/cloudera/.c9/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/cloudera/.c9/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile

**Comment by kevinmustaqim** [comment]
could anyone tell me what was actually happen, today i cannot save anything

http://prntscr.com/8gho4t
