### ISSUE TITLE
can't install on mac

### ISSUE THREAD

**Issue by soitun** [c9/core#129]
MacBook-Pro:c9sdk $ ./server.js -p 8080 -l 0.0.0.0 -a :
Starting standalone
module.js:338
    throw err;
          ^
Error: Cannot find module '../plugins/c9.ide.run/runners_list'
    at Module._resolveFilename (module.js:336:15)
    at Function.modules._resolveFilename (/Users/soitun/c9sdk/node_modules/c9/setup_paths.js:20:12)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/soitun/c9sdk/settings/standalone.js:11:19)
    at start (/Users/soitun/c9sdk/server.js:126:77)
    at /Users/soitun/c9sdk/server.js:93:13
    at /Users/soitun/c9sdk/node_modules/async/lib/async.js:122:13
    at _each (/Users/soitun/c9sdk/node_modules/async/lib/async.js:46:13)

**Comment by nightwing** [comment]
what error did you get when running `scripts/install.sdk.sh` ?

**Comment by nightwing** [comment]
Closing since there isn't sufficient information to debug this. 
The stacktrace above just means that c9.ide.run plugin haven't been installed for some reason
Please feel free to comment/reopen if you have any questions or additional information.
