### ISSUE TITLE
run.run: "Cannot read property 'map' of undefined" error

### ISSUE THREAD

**Issue by serkanserttop** [c9/core#135]
I can't get the below code to work.
It is taken straight from the [apidocs](https://docs.c9.io/api/#!/api/run).

        var process = run.run("auto", {
			path: "/server.js"
		}, function(err, pid) {
			console.log("in the process callback");
		});

I don't get the "in the process callback" log.
The error I get is below.

Uncaught TypeError: Cannot read property 'map' of undefined
******/config/workspace-nodejs.js:14202 

Error in my local setup is in kaefer/reliable_socket.js#129:

            TypeError: Cannot read property 'map' of undefined
            at bashQuote (http://localhost:8181/static/plugins/c9.ide.run/run.js:814:31)
            at getVariable (http://localhost:8181/static/plugins/c9.ide.run/run.js:436:28)
            at http://localhost:8181/static/plugins/c9.ide.run/run.js:486:48
            at String.replace (native)
            at insertVariables (http://localhost:8181/static/plugins/c9.ide.run/run.js:483:31)
            at http://localhost:8181/static/plugins/c9.ide.run/run.js:325:27
            at Array.map (native)
            at run (http://localhost:8181/static/plugins/c9.ide.run/run.js:304:30)
            at http://localhost:8181/static/plugins/c9.ide.run/run.js:286:25
            at done (http://localhost:8181/static/plugins/c9.ide.run/run.js:115:32)

**Comment by serkanserttop** [comment]
Moved [here](https://github.com/c9/c9.ide.run/issues/9)
