### ISSUE TITLE
`Error creating TMUX session` preventing proper-functioning of local sdk

### ISSUE THREAD

**Issue by ggoodman** [c9/core#140]
![image](https://cloud.githubusercontent.com/assets/50030/9583470/84c112ec-4fd9-11e5-98fa-0cf669c05b3c.png)

Also seeing:

![image](https://cloud.githubusercontent.com/assets/50030/9583501/b353fad4-4fd9-11e5-9e10-4d4d354ad9ae.png)

**Comment by nightwing** [comment]
@ggoodman was this working before, or is this a new installation?
this error can happen either if tmux or ~/.c9/node_modules/pty.js are broken.

**Comment by ggoodman** [comment]
I regularly update the sdk. This broke when taking updates from over the
weekend. Can you suggest how I could detect which of the issues you noted
might be causing this?

**Comment by nightwing** [comment]
check from terminal if  `~/.c9/bin/tmux` works 
if it works, look what errors are printed when running `node server.js`
if pty.js is broken there must be some output from https://github.com/c9/core/blob/master/node_modules/vfs-local/localfs.js#L74

try adding `console.error(process.execPath, process.version)` there.

running install.sh from https://github.com/c9/install/blob/master/install.sh might fix the issue too.

**Comment by ggoodman** [comment]
The issue appears to be unique to the OSX build generated by
`./scripts/setup-local-dev.sh`. I have no issue when running as a local
server and viewing via the browser.

I tried:

1. `~/.c9/bin/tmux` and the binary appears to work w/o issue.
2. `c9/install`: I ran that locally and it completed without error, however
it did not appear to affect the underlying issue.

Thoughts?

**Comment by nightwing** [comment]
is  `~/.c9/node_modules/pty.js/node_modules/extend` module missing?

If no, could you add `console.error(process.execPath, process.version) ` to https://github.com/c9/core/blob/master/node_modules/vfs-local/localfs.js#L74 and tell me what error is printed in the console.

Seems like local version starts server using wrong node, but i do not see why it would start to happen this weekend.

**Comment by ggoodman** [comment]
Perhaps this may give an additional hint:

![image](https://cloud.githubusercontent.com/assets/50030/9588257/418eb51c-4ff5-11e5-87ad-014370038385.png)

It appears that https://github.com/c9/core/blob/master/node_modules/vfs-local/localfs.js#L74 is not even being included. I tried throwing the statement you suggested as well as a `debugger` statement in there to no avail. I scanned the tree of files from the dev console and didn't see `vfs-local` in there.

I ran the command you suggested in devtools console:

```/Users/ggoodman/Projects/c9sdk/build/Cloud9-dev.app/Contents/Frameworks/node-webkit Helper.app/Contents/MacOS/node-webkit Helper v0.11.9 ```

**Comment by nightwing** [comment]
Thank you.  This helps to rule out version about using wrong node
Could you try commenting out https://github.com/c9/core/blob/master/configs/local.js#L4-L9 it is the only real difference between local and standalone server.
`ls ~/.c9/node_modules/pty.js/node_modules` might be helpful too

> localfs  is not even being included.

localfs is not included in files loaded into nw.js app, which only has client side files.
localfs runs in a separate nodejs process.

**Comment by ggoodman** [comment]
```shell
ggoodman@Geoffreys-MacBook-Pro:~ $ ls -la ~/.c9/node_modules/pty.js/node_modules
total 0
drwxr-xr-x   4 ggoodman  staff   136B 31 Aug 13:00 ./
drwxr-xr-x  15 ggoodman  staff   510B 31 Aug 13:00 ../
drwxr-xr-x   7 ggoodman  staff   238B 31 Aug 13:00 extend/
drwxr-xr-x  15 ggoodman  staff   510B 31 Aug 13:00 nan/
ggoodman@Geoffreys-MacBook-Pro:~ $ jq '.dependencies' ~/.c9/node_modules/pty.js/package.json
{
  "extend": "~1.2.1",
  "nan": "^1.8.4"
}
```

Commenting out those lines gave me what appears to be a functional IDE but lots of errors in console.

I'm experimenting with full re-install. Are there any artifacts stored outside the sdk dir and `~/.c9`?

**Comment by ggoodman** [comment]
Issue remains on a completely fresh install

```
rm -rf ~/.c9
rm -rf c9sdk
git clone https://github.com/c9/core c9sdk
cd c9sdk
./scripts/install-sdk.sh
./scripts/setup-local-dev.sh
```

Issue remains. 

One thing that changed fairly recently is that I moved to 2FA for Github authentication.

**Comment by nightwing** [comment]
Only files in sdk dir and ~/.c9 are used by sdk.

> Commenting out those lines gave me what appears to be a functional IDE but lots of errors in console.

what errors? it may show some of log from server as error.

This issue must be caused by https://github.com/c9/core/commit/ae6e89f36b6b5ba477117f0b4e7a2c436e87b517#diff-637c0aa9543a8619b46943cb0fbc231fR15, thanks for helping to find it!

**Comment by ggoodman** [comment]
Sorry about the format. Copy/paste from the devtools:

```
SERVER: Starting local
 /Users/ggoodman/Projects/c9sdk/local/server.js:201
Starting local
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
SERVER: Starting local
 /Users/ggoodman/Projects/c9sdk/local/server.js:201
Starting local
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
SERVER: Connect server listening at http://localhost:49221
 /Users/ggoodman/Projects/c9sdk/local/server.js:201
Connect server listening at http://localhost:49221
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
SERVER: CDN: version standalone initialized /Users/ggoodman/Projects/c9sdk/build
 /Users/ggoodman/Projects/c9sdk/local/server.js:201
CDN: version standalone initialized /Users/ggoodman/Projects/c9sdk/build
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
SERVER: Started '/Users/ggoodman/Projects/c9sdk/configs/local' with config 'local'!
 /Users/ggoodman/Projects/c9sdk/local/server.js:201
Started '/Users/ggoodman/Projects/c9sdk/configs/local' with config 'local'!
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
cache /Users/ggoodman/Projects/c9sdk/build/standalone/skin/default-local/flat-light.css
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
cache hit /Users/ggoodman/Projects/c9sdk/build/standalone/skin/default-local/flat-light.css
 /Users/ggoodman/Projects/c9sdk/local/server.js:214
GET https://api.c9.io/user/?access_token=fake_token 401 (Unauthorized) http-xhr.js:97
HTTP error 401: {"error":{"code":401,"status":"Unauthorized","message":"401: Unauthorized","hostname":"newclient-gce-usw-32-prod","scope":"api","defaultMessage":"Unauthorized"}} http-xhr.js:127
detach 3 undefined repl.js:351
[language] Sent to worker (switchFile): tab2 length: 3 language.js:148
[language] Sent to worker (documentOpen): tab2 length: 3 language.js:148
TypeError {stack: (...), message: "Cannot read property '1' of null"} /Users/ggoodman/Projects/c9sdk/local/server.js:1059
41403: Error: ENOENT, stat '/Users/ggoodman/.c9/plugins/'
    at Error (native)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
41403: Error: ENOENT, stat '/Users/ggoodman/.c9/managed/plugins/'
    at Error (native)
41403: Error: ENOENT, stat '/Users/ggoodman/.c9/dev/plugins/'
    at Error (native)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/home/.c9/plugins/?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, stat '/Users/ggoodman/.c9/plugins/'
    at Error (native)
 http-xhr.js:127
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/home/.c9/managed/plugins/?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, stat '/Users/ggoodman/.c9/managed/plugins/'
    at Error (native)
 http-xhr.js:127
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/home/.c9/dev/plugins/?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, stat '/Users/ggoodman/.c9/dev/plugins/'
    at Error (native)
 http-xhr.js:127
41403: Error: ENOENT, stat '/Users/ggoodman/Projects/webtask/auth0-sandbox-ops/New Folder/'
    at Error (native)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/workspace/Users/ggoodman/Projects/webtask/auth0-sandbox-ops/New%20Folder/?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, stat '/Users/ggoodman/Projects/webtask/auth0-sandbox-ops/New Folder/'
    at Error (native)
 http-xhr.js:127
41403: Error: ENOENT, stat '/Users/ggoodman/Projects/webtask/auth0-sandbox-ops/lib/'
    at Error (native)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/workspace/Users/ggoodman/Projects/webtask/auth0-sandbox-ops/lib/?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, stat '/Users/ggoodman/Projects/webtask/auth0-sandbox-ops/lib/'
    at Error (native)
 http-xhr.js:127
41403: Error: ENOENT, open '/Users/ggoodman/Projects/webtask/.c9/project.settings'
    at Error (native)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/workspace/Users/ggoodman/Projects/webtask/.c9/project.settings?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, open '/Users/ggoodman/Projects/webtask/.c9/project.settings'
    at Error (native)
 http-xhr.js:127
[language] Sent to worker (documentOpen): /Users/ggoodman/Projects/wt-cli/bin/create.js length: 395 language.js:148
[language] Sent to worker (switchFile): /Users/ggoodman/Projects/wt-cli/bin/create.js length: 395 language.js:148
[language] Sent to worker (documentOpen): /Users/ggoodman/Projects/wt-cli/bin/create.js length: 395 language.js:148
PubSub connected pubsub-client.js:43
41403: Error: Command failed: mkdir -p /.c9/metadata/workspace/Users/ggoodman/Projects/wt-cli/bin
mkdir: /.c9/metadata/workspace/Users/ggoodman/Projects/wt-cli/bin: Permission denied

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
41403: Error: Command failed: mkdir -p /.c9/metadata/
mkdir: /.c9/metadata/: Permission denied

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
Error: 'nak' utility failed with exit code 1 and stderr: '/Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:75
    statAction(fs.lstatSync(fpath + filepath));
                                  ^
Error: EACCES, permission denied '//Library/Caches/com.apple.Spotlight/schema.501.plist'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at statter (/Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:75:19)
    at readdirAction (/Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:85:7)
    at /Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:93:7
    at FSReqWrap.oncomplete (fs.js:95:15)
'
    at EventEmitter.<anonymous> (/Users/ggoodman/Projects/c9sdk/plugins/c9.vfs.server/filelist.js:99:31)
    at EventEmitter.emit (events.js:110:17)
    at Parent.onExit (/Users/ggoodman/Projects/c9sdk/node_modules/vfs-socket/consumer.js:271:17)
    at Parent.Agent._onMessage (/Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:471:8)
    at Transport.emit (events.js:107:17)
    at /Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:96:14
    at parse (/Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:252:21)
    at Socket.onData (/Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:101:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/home/.c9/file.listing?pathToN…FUsers%2Fggoodman%2FProjects%2Fwt-cli&limit=100000&access_token=fake_token 500 (Internal Server Error) http-xhr.js:97
HTTP error 500: Error: 'nak' utility failed with exit code 1 and stderr: '/Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:75
    statAction(fs.lstatSync(fpath + filepath));
                                  ^
Error: EACCES, permission denied '//Library/Caches/com.apple.Spotlight/schema.501.plist'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at statter (/Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:75:19)
    at readdirAction (/Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:85:7)
    at /Users/ggoodman/Projects/c9sdk/node_modules/nak/lib/walkdir.js:93:7
    at FSReqWrap.oncomplete (fs.js:95:15)
'
    at EventEmitter.<anonymous> (/Users/ggoodman/Projects/c9sdk/plugins/c9.vfs.server/filelist.js:99:31)
    at EventEmitter.emit (events.js:110:17)
    at Parent.onExit (/Users/ggoodman/Projects/c9sdk/node_modules/vfs-socket/consumer.js:271:17)
    at Parent.Agent._onMessage (/Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:471:8)
    at Transport.emit (events.js:107:17)
    at /Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:96:14
    at parse (/Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:252:21)
    at Socket.onData (/Users/ggoodman/Projects/c9sdk/node_modules/smith/smith.js:101:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16) http-xhr.js:127
Error {code: "EACCES", status: 500, stack: (...), message: "Error: 'nak' utility failed with exit code 1 and s… at readableAddChunk (_stream_readable.js:163:16)"}
 navigate.js:434
[language] Sent to worker (switchFile): /Users/ggoodman/Projects/wt-cli/bin/create.js length: 395 language.js:148
[language] Sent to worker (documentOpen): /Users/ggoodman/Projects/wt-cli/bin/create.js length: 13537 language.js:148
[language] Sent to worker (documentOpen): tab2 length: 188 language.js:148
41403: Error: ENOENT, open '/Users/ggoodman/Projects/c9sdk/version'
    at Error (native)
 /Users/ggoodman/Projects/c9sdk/local/server.js:211
GET http://localhost:49221/vfs/2/9crDb1jtlfT9W9pM/workspace/Users/ggoodman/Projects/c9sdk/version?access_token=fake_token 404 (Not Found) http-xhr.js:97
HTTP error 404: 41403: Error: ENOENT, open '/Users/ggoodman/Projects/c9sdk/version'
    at Error (native)
```

**Comment by ggoodman** [comment]
@nightwing I'm now seeing this issue with a newly deployed `ssh` server using the paid service via the browser.

**Comment by nightwing** [comment]
@ggoodman could you write ping support@c9.io telling on which workspace this happens, (use `Support>Get Help>send support request..,` menu item)
It's most likely some error in installer.
The code causing this error in local doesn't run on ssh (i have a pull request with a fix for this pending review)

**Comment by ggoodman** [comment]
FYI: I use the following to provision a Docker container on a CoreOS host:

https://github.com/ggoodman/cloud9_coreos_ssh_workspace/blob/master/Dockerfile#L44

**Comment by nightwing** [comment]
I see. It may be something on our side, but still if you tell me the workspace name via support, it would be much easier to debug.

**Comment by ggoodman** [comment]
@nightwing I've been able to get the editor working again by 'reverting' this change: https://github.com/c9/install/commit/c25a79badfe37ada7cdaa80b28e6e83834eeeb61#diff-3fbb47e318cd8802bd325e7da9aaabe8R394

**Comment by nightwing** [comment]
@ggoodman are you installing it on arm or x86 system?

**Comment by ggoodman** [comment]
```
Geoffreys-MacBook-Pro:.c9 ggoodman$ uname -a
Darwin Geoffreys-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by ggoodman** [comment]
Seems to all be fixed up lately.

**Comment by askucher** [comment]
I have this issue for non-root user
