### ISSUE TITLE
--packed => Error: Cannot find module 'node_modules/salesforce.language/__worker__'

### ISSUE THREAD

**Issue by cadorn** [c9/core#148]
Running latest clone on nodejs 0.12 I get:
````
module.js:338
    throw err;
    ^
Error: Cannot find module 'node_modules/salesforce.language/__worker__'
    at Module._resolveFilename (module.js:336:15)
    at Function.modules._resolveFilename (.../c9/core/node_modules/c9/setup_paths.js:26:12)
````

**Comment by cadorn** [comment]
Seems to break when `--packed` is specified. Works without it.

**Comment by nightwing** [comment]
Fixed by https://github.com/c9/core/commit/6d8ac4b5dd375326aaabcd4eeda707b91602fa2c, thanks for the report.
