### ISSUE TITLE
How install c9core on Windows?

### ISSUE THREAD

**Issue by khusamov** [c9/core#205]

**Comment by nightwing** [comment]
Clone the repo and run install-sdk.sh from git bash
It will download all dependencies from https://github.com/cloud9ide/sdk-deps-win32 (see https://github.com/c9/core/blob/master/scripts/install-sdk.sh#L136) and doesn't require visual studio.
Make sure that HOME variable is always the same when installing and launching cloud9.
When HOME is empty cloud9 uses ` process.env.HOME = process.env.HOMEDRIVE + process.env.HOMEPATH;` instead https://github.com/c9/core/blob/master/settings/standalone.js#L19

**Comment by khusamov** [comment]
Thank you! Everything worked out! )

But there are some problems.
1) When the errors occurred. It is necessary to install Python?

```bash
--- Running npm install --------------------------------------------
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-connect will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN engine simplefunc@0.0.2: wanted: {"node":">= 0.6.0 && < 0.9.0"} (current: {"node":"4.1.0","npm":"2.14.3"})

> ws@0.4.31 install C:\Users\khusamov\cloud9sdk\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\khusamov\cloud9sdk\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

> bufferutil@1.2.1 install C:\Users\khusamov\cloud9sdk\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

|
C:\Users\khusamov\cloud9sdk\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\khusamov\cloud9sdk\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\khusamov\cloud9sdk\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

-
C:\Users\khusamov\cloud9sdk\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\khusamov\cloud9sdk\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install C:\Users\khusamov\cloud9sdk\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\khusamov\cloud9sdk\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\khusamov\cloud9sdk\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install C:\Users\khusamov\cloud9sdk\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\khusamov\cloud9sdk\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\khusamov\cloud9sdk\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
```

**Comment by khusamov** [comment]
2) After starting the permanent error occurs:

**Failed to write to 'state.settings'. File or folder 'state.settings' does not exist.**

Here's a screenshot:

![default](https://cloud.githubusercontent.com/assets/4146998/10997188/15ace2e4-849c-11e5-8fe8-c9e1357b4fd0.PNG)

```bash
4576: Error: spawn mkdir ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
4576: Error: ENOENT, lstat 'C:\Users\khusamov\cloud9sdk\.c9'
    at Error (native)
4576: Error: spawn mkdir ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
4576: Error: ENOENT, lstat 'C:\Users\khusamov\cloud9sdk\.c9'
    at Error (native)
4576: Error: ENOENT, lstat 'C:\Users\khusamov\cloud9sdk\.c9'
    at Error (native)
4576: Error: ENOENT, lstat 'C:\Users\khusamov\cloud9sdk\.c9'
    at Error (native)
4576: Error: spawn mkdir ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
4576: Error: ENOENT, lstat 'C:\Users\khusamov\cloud9sdk\.c9'
    at Error (native)
4576: Error: spawn mkdir ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
4576: Error: ENOENT, lstat 'C:\Users\khusamov\cloud9sdk\.c9'
    at Error (native)
```

**Comment by nightwing** [comment]
binary modules in ws and engine.io are optional, so it should work without them too.
`mkdir ENOENT` errors look like an issue with installer and server.js getting different home directories.
Which version of msys git do you use? is there `'C:\Users\khusamov\.c9\msys'` folder?

**Comment by khusamov** [comment]
```bash
khusamov@Kosmos MINGW64 ~
$ git --version
git version 2.6.1.windows.1
```
![default](https://cloud.githubusercontent.com/assets/4146998/10997831/7ca82396-84a1-11e5-9e83-8c3f669c65ca.PNG)

**Comment by nightwing** [comment]
Could you try changing https://github.com/c9/core/blob/master/settings/standalone.js#L18-L22 to 

    if (win32) {
        if (process.env.HOME === undefined)
            process.env.HOME = process.env.HOMEDRIVE + process.env.HOMEPATH;
        if (!/msys\/bin|Git\/bin/.test(process.env.PATH))
            process.env.PATH = path.join(process.env.HOME, ".c9", "msys/bin") + ";" + process.env.PATH;
    }

**Comment by khusamov** [comment]
Working!
The settings are saved.
Folder ".c9" appeared:

![default](https://cloud.githubusercontent.com/assets/4146998/10998246/d28b4b5a-84a4-11e5-8249-eb0921c7f0b2.PNG)

Log:

```bash
Starting standalone
Connect server listening at http://127.0.0.1:8181
CDN: version standalone initialized C:\Users\khusamov\cloud9sdk\build
Started 'C:\Users\khusamov\cloud9sdk\configs\standalone' with config 'standalone'!
cache C:\Users\khusamov\cloud9sdk\build\standalone\skin\default\flat-light.css
cache hit C:\Users\khusamov\cloud9sdk\build\standalone\skin\default\flat-light.css
13208: Error: ENOENT, stat 'C:\Users\khusamov\.c9\plugins'
    at Error (native)
13208: Error: ENOENT, stat 'C:\Users\khusamov\.c9\managed\plugins'
    at Error (native)
13208: Error: ENOENT, stat 'C:\Users\khusamov\.c9\dev\plugins'
    at Error (native)
13208: Error: ENOENT, open 'C:\Users\khusamov\cloud9sdk\.c9\project.settings'
    at Error (native)
cache C:\Users\khusamov\cloud9sdk\build\standalone\skin\default\flat-light.css
cache hit C:\Users\khusamov\cloud9sdk\build\standalone\skin\default\flat-light.css
13208: Error: ENOENT, stat 'C:\Users\khusamov\.c9\plugins'
    at Error (native)
13208: Error: ENOENT, stat 'C:\Users\khusamov\.c9\managed\plugins'
    at Error (native)
13208: Error: ENOENT, stat 'C:\Users\khusamov\.c9\dev\plugins'
    at Error (native)
13208: Error: ENOENT, open 'C:\Users\khusamov\cloud9sdk\.c9\metadata\tab1'
    at Error (native)
```

**Comment by nightwing** [comment]
Applied that change in https://github.com/c9/core/commit/27649eab80f24f6deaaa594f050f659684cfefdb
