### ISSUE TITLE
Error: Cannot find module '../plugins/c9.ide.run/runners_list'

### ISSUE THREAD

**Issue by xvinc** [c9/core#249]
Error: Cannot find module '../plugins/c9.ide.run/runners_list'
    at Module._resolveFilename (module.js:326:15)
    at Function.modules._resolveFilename (C:\Users\xvinc\Desktop\c9sdk\node_modu
les\c9\setup_paths.js:26:12)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\xvinc\Desktop\c9sdk\settings\standalone.js:11:19
)
    at start (C:\Users\xvinc\Desktop\c9sdk\server.js:158:77)
    at C:\Users\xvinc\Desktop\c9sdk\server.js:125:13
    at C:\Users\xvinc\node_modules\async\lib\async.js:111:13
    at Array.forEach (native)

**Comment by nightwing** [comment]
This can happen if './scripts/install-sdk.sh' didn't complete successfully, try running it again, to see what error it prints out.

**Comment by nightwing** [comment]
fixed in https://github.com/c9/c9.ide.run/commit/4f0257bc0bc2ce6577398bfc4886b96e262af4a8
