### ISSUE TITLE
Do not start the "node server.js"

### ISSUE THREAD

**Issue by khusamov** [c9/core#259]
```
C:\Users\khusa\c9ide>node server.js
Starting standalone
Syntax error in runner C:\Users\khusa\c9ide\plugins\c9.ide.run/runners-docker/C (simple).run [SyntaxError: Unexpected token .]
C:\Users\khusa\c9ide\plugins\c9.ide.run\runners_list.js:12
            throw e;
            ^

SyntaxError: Unexpected token .
    at Object.parse (native)
    at C:\Users\khusa\c9ide\plugins\c9.ide.run\runners_list.js:9:25
    at Array.forEach (native)
    at readRunners (C:\Users\khusa\c9ide\plugins\c9.ide.run\runners_list.js:6:33)
    at Object.<anonymous> (C:\Users\khusa\c9ide\plugins\c9.ide.run\runners_list.js:26:13)
    at Module._compile (module.js:413:34)
    at Module.module.constructor._compile (C:\Users\khusa\c9ide\node_modules\amd-loader\amd-loader.js:10:31)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by nightwing** [comment]
fixed in https://github.com/c9/c9.ide.run/commit/4f0257bc0bc2ce6577398bfc4886b96e262af4a8
