### ISSUE TITLE
cannot set --readonly at startup option due to file missing

### ISSUE THREAD

**Issue by mmis1000** [c9/core#285]
log for the error
```
data:    server.js:25813 - Error: Cannot find module '/home/mmis1000/c9sdk/plugins/c9.vfs.standalone/../../configs/client-default-ro.js'
data:    server.js:25813 -     at Module._resolveFilename (module.js:325:15)
data:    server.js:25813 -     at Function.modules._resolveFilename (/home/mmis1000/c9sdk/node_modules/c9/setup_paths.js:26:12)
data:    server.js:25813 -     at Function.Module._load (module.js:276:25)
data:    server.js:25813 -     at Module.require (module.js:353:17)
data:    server.js:25813 -     at require (internal/module.js:12:17)
data:    server.js:25813 -     at getConfig (/home/mmis1000/c9sdk/plugins/c9.vfs.standalone/standalone.js:390:12)
data:    server.js:25813 -     at /home/mmis1000/c9sdk/plugins/c9.vfs.standalone/standalone.js:116:30
data:    server.js:25813 -     at processNext (/home/mmis1000/c9sdk/node_modules/frontdoor/lib/section.js:205:13)
data:    server.js:25813 -     at /home/mmis1000/c9sdk/node_modules/frontdoor/lib/section.js:209:17
data:    server.js:25813 -     at decodeParams (/home/mmis1000/c9sdk/node_modules/frontdoor/lib/route.js:262:9)
data:    server.js:25813 - Error: Cannot find module '/home/mmis1000/c9sdk/plugins/c9.vfs.standalone/../../configs/client-default-ro.js'
data:    server.js:25813 -     at Module._resolveFilename (module.js:325:15)
data:    server.js:25813 -     at Function.modules._resolveFilename (/home/mmis1000/c9sdk/node_modules/c9/setup_paths.js:26:12)
data:    server.js:25813 -     at Function.Module._load (module.js:276:25)
data:    server.js:25813 -     at Module.require (module.js:353:17)
data:    server.js:25813 -     at require (internal/module.js:12:17)
data:    server.js:25813 -     at getConfig (/home/mmis1000/c9sdk/plugins/c9.vfs.standalone/standalone.js:390:12)
data:    server.js:25813 -     at /home/mmis1000/c9sdk/plugins/c9.vfs.standalone/standalone.js:116:30
data:    server.js:25813 -     at processNext (/home/mmis1000/c9sdk/node_modules/frontdoor/lib/section.js:205:13)
data:    server.js:25813 -     at /home/mmis1000/c9sdk/node_modules/frontdoor/lib/section.js:209:17
data:    server.js:25813 -     at decodeParams (/home/mmis1000/c9sdk/node_modules/frontdoor/lib/route.js:262:9)
```
it seems it require a tweeked config `client-default-ro.js` , but there isn't

**Comment by mmis1000** [comment]
Ok, solved by write a new `client-default-ro.js` .
against the one in official site's read only mode.

now, there is a new problem.
the client trys to access to
```
    /api/collab/0/access_info?access_token=token
```
in readonly mode for author information.

But there isn't such mock for it.
results in a error at startup

![pic for the error](http://puu.sh/okxAh/f8eb0e83ed.png)
