### ISSUE TITLE
standalone.js error with split

### ISSUE THREAD

**Issue by onaclov2000** [c9/core#294]
When trying to run the command 

     node server.js -p 8080 -a

I got the following error.

      /home/hotdog/c9sdk/configs/standalone.js:108
        var auth = (argv.auth || ":").split(":");
                                   ^

    TypeError: (argv.auth || ":").split is not a function
        at module.exports (/home/hotdog/c9sdk/configs/standalone.js:108:35)
        at start (/home/hotdog/c9sdk/server.js:192:38)
        at /home/hotdog/c9sdk/server.js:125:13
        at /home/hotdog/c9sdk/node_modules/async/lib/async.js:122:13
        at _each (/home/hotdog/c9sdk/node_modules/async/lib/async.js:46:13)
        at Object.async.each (/home/hotdog/c9sdk/node_modules/async/lib/async.js:121:9)
        at startConfigs (/home/hotdog/c9sdk/server.js:122:15)
        at main (/home/hotdog/c9sdk/server.js:115:5)
        at main (/home/hotdog/c9sdk/server.js:100:16)
        at Object.<anonymous> (/home/hotdog/c9sdk/server.js:55:5)

I was able to work around this by adding a + '' next to argv.auth.

     var auth = (argv.auth + '' || ":").split(":");

I am running node v4.4.3

installed from here:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

on Ubuntu 15.10

I don't know all the appropriate testing, but that should be the fix, not sure if it's a problem across installs.

**Comment by onaclov2000** [comment]
I mostly am leaving this here as an issue, incase others install and see the same problem, it's searchable. Whoever the powers that be may close this if there is no need to update for others.

**Comment by phouverneyuff** [comment]
+1

**Comment by nightwing** [comment]
It needs to be invoked with `-a :` 
https://github.com/c9/core/commit/c9a1efeeaa1b8f35ecd32ef33711f2ab7b9178df makes the error less confusing.
