### ISSUE TITLE
New installation not working.

### ISSUE THREAD

**Issue by k0nsl** [c9/core#311]
Specifications of the server:

```bash
         _,met$$$$$gg.           root@S1NE23
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 8.4 jessie
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 3.16.0-4-amd64
   ,$$P'              `$$$.      Uptime: 106d 13h 30m
  ',$$P       ,ggs.     `$$b:    Packages: 806
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.3.30
   $$P      d$'     ,    $$P     CPU: Intel Core2 Quad CPU Q6600 @ 2.403GHz
   $$:      $$.   -    ,d$$'     RAM: 1756MB / 3954MB
   $$\;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""

```

Node.js version: v0.12.14

It installs itself accordingly and without any issues, following these steps:

```
git clone git://github.com/c9/core.git c9sdk
cd c9sdk
scripts/install-sdk.sh
```

I start the instance with this command: node server.js -p 8081 --listen 127.0.0.1 -a k0nsl:k0nsl

When I visit the IP via Chrome I see the logo and some text beneath it, but that's all.

In my developer console it's not looking good:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
Couldn't load module lib/tern_from_ts/defs/__list.json XMLHttpRequest
Failed to load resource: the server responded with a status of 499 (unknown)
HTTP error 499: {"error":{"code":499,"scope":"standalone","message":"VFS connection does not exist"}}
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Object.main [as setup] (http://127.0.0.1:8081/static/plugins/c9.ide.language.javascript.tern/tern.js:14:32)
    at startPlugins (http://127.0.0.1:8081/static/lib/architect/architect.js:470:24)
    at startPlugins (http://127.0.0.1:8081/static/lib/architect/architect.js:478:21)
    at register (http://127.0.0.1:8081/static/lib/architect/architect.js:509:13)
    at http://127.0.0.1:8081/static/plugins/c9.ide.layout.classic/preload.js:77:13
    at http://127.0.0.1:8081/static/plugins/c9.ide.layout.classic/preload.js:58:21
    at _require (http://127.0.0.1:8081/static/mini_require.js:232:41)
    at http://127.0.0.1:8081/static/mini_require.js:131:13
    at Array.forEach (native)
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Object.main [as setup] (http://127.0.0.1:8081/static/plugins/c9.ide.language.javascript.tern/tern.js:14:32)
    at startPlugins (http://127.0.0.1:8081/static/lib/architect/architect.js:470:24)
    at startPlugins (http://127.0.0.1:8081/static/lib/architect/architect.js:478:21)
    at register (http://127.0.0.1:8081/static/lib/architect/architect.js:509:13)
    at http://127.0.0.1:8081/static/plugins/c9.ide.layout.classic/preload.js:77:13
    at http://127.0.0.1:8081/static/plugins/c9.ide.layout.classic/preload.js:58:21
    at _require (http://127.0.0.1:8081/static/mini_require.js:232:41)
    at http://127.0.0.1:8081/static/mini_require.js:131:13
    at Array.forEach (native)
Uncaught SyntaxError: Unexpected token u in JSON at position 0
PubSub connected
GET http://127.0.0.1:8081/static/lib/tern/lib/infer.js 404 (Not Found)
Could not load language handler plugins/c9.ide.language.javascript.tern/worker/architect_resolver_worker: NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:8081/static/lib/tern/lib/infer.js' failed to load.
Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:8081/static/lib/tern/lib/infer.js' failed to load.
    at Error (native)
    at require (http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:79:5)
    at req (http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:130:23)
    at http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:146:44
    at Array.map (native)
    at Object.window.require.modules.(anonymous function).factory (http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:137:58)
    at require (http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:66:37)
    at require (http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:80:19)
    at req (http://127.0.0.1:8081/static/lib/ace/lib/ace/worker/worker.js:130:23)
    at Object.<anonymous> (http://127.0.0.1:8081/static/plugins/c9.ide.language.javascript.tern/worker/architect_resolver_worker.js:4:14)
Object {message: "Uncaught NetworkError: Failed to execute 'importSc…081/static/lib/tern/lib/infer.js' failed to load.", data: undefined, file: "http://127.0.0.1:8081/static/plugins/c9.ide.language/worker.js", line: 330, col: 17…} Object {}
```

I am just submitting this hastily and can supplement with more information, if needed.

Best wishes,
-k0nsl

**Comment by nightwing** [comment]
looks like there was an error during npm install, try running scripts/install-sdk.sh again, sometimes it may fail if security restrictions on number of processes are too strict

**Comment by k0nsl** [comment]
@nightwing: thanks for the response.

Yes, I just noticed the following while re-running `install-sdk.sh`:
```
npm ERR! Command failed: git clone --template=/root/.c9/tmp/.npm/_git-remotes/_templates --mirror git://github.com/cloud9ide/tern.git /root/.c9/tmp/.npm/_git-remotes/git-github-com-cloud9ide-tern-git-bd4c6776
npm ERR! Cloning into bare repository '/root/.c9/tmp/.npm/_git-remotes/git-github-com-cloud9ide-tern-git-bd4c6776'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.123]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/core/npm-debug.log
```

I see similar errors such as the one above for other repositories in the cloud9ide account. But I don't get why? I assume they exist (I haven't bothered to check). I don't have any problems cloning from GH, as I just cloned `core` earlier today, and never had any problems with connections to GH prior to this.

**Comment by thurt** [comment]
I also installed for the first time. I am getting the exact same errrors
```
Couldn't load module lib/tern_from_ts/defs/__list.json XMLHttpRequest
```
and
```
SyntaxError: Unexpected token u in JSON at position 0
```
and 
```
npm ERR! Command failed: git clone --template=/root/.c9/tmp/.npm/_git-remotes/_templates --mirror git://github.com/cloud9ide/tern.git /root/.c9/tmp/.npm/_git-remotes/git-github-com-cloud9ide-tern-git-bd4c6776
npm ERR! Cloning into bare repository '/root/.c9/tmp/.npm/_git-remotes/git-github-com-cloud9ide-tern-git-bd4c6776'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.123]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/core/npm-debug.log
```

**Comment by thurt** [comment]
My install errors all seem to be related to the npm dependencies with uri `git://`. I get github.com errno=Connection timed out for these.
```
"emmet": "git://github.com/cloud9ide/emmet-core.git#2ff6dc06ad",

"nak": "git://github.com/cloud9ide/nak.git#6deef931594",

"tern": "git://github.com/cloud9ide/tern.git#39015d544d4c00c7899fea4c95c2e5bc2720e68e",
"tern_from_ts": "git://github.com/cloud9ide/tern_from_ts.git#84d51dcb9b16b126a206789d4d4237cde2801fe4"
```

**Comment by thurt** [comment]
@k0nsl I resolved my issues by changing git configuration. Using this command at the console:
```
git config --global url."https://".insteadOf git://
```

I am behind a firewall that doesn't allow `git://` protocol/port. So this config changes git to always use `https://`. 

Also, I didn't go through the full install again. I simply installed these errored packages directly using npm:
```
npm i https://github.com/cloud9ide/emmet-core.git#2ff6dc06ad
npm i https://github.com/cloud9ide/nak.git#6deef931594
npm i https://github.com/cloud9ide/tern.git#39015d544d4c00c7899fea4c95c2e5bc2720e68e
npm i https://github.com/cloud9ide/tern_from_ts.git#84d51dcb9b16b126a206789d4d4237cde2801fe4
```

Following these steps got me into the editor. I haven't tested significantly beyond this.

**Comment by k0nsl** [comment]
I finally got it working on another VM on another network. It's looking good :)

Keep up the good work!
