### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by herohamp** [c9/core#382]
ampton@ubuntuPowerEdge:~/c9sdk$ node ./server.js -p 8080 -l 0.0.0.0 -a :

module.js:340
    throw err;
          ^
Error: Cannot find module 'async'
    at Module._resolveFilename (module.js:338:15)
    at Function.modules._resolveFilename (/home/hampton/c9sdk/node_modules/c9/setup_paths.js:26:12)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at main (/home/hampton/c9sdk/server.js:75:17)
    at Object.<anonymous> (/home/hampton/c9sdk/server.js:55:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by nightwing** [comment]
was there an error when running ./scripts/install-sdk.sh?
async module missing means npm install didn't complete

**Comment by herohamp** [comment]
ok thanks, I ended up figuring it out, turns out I needed to update nodes and a few other stuff
