### ISSUE TITLE
After duplicating view, closing parent tab causes error

### ISSUE THREAD

**Issue by ozcanovunc** [c9/core#387]
- Assume there is only one tab on the pane. 
<img src="https://cloud.githubusercontent.com/assets/13097409/21674225/71a27b20-d335-11e6-8c2a-b4b35ab1f6f4.png" width="200">

- Right click to "Duplicate View"
<img src="https://cloud.githubusercontent.com/assets/13097409/21674226/71bbadde-d335-11e6-94d2-d4344ae6f711.png" width="200">

- Close first tab which is the parent
- This will close both tabs, but the problem is the pane turns black after that.
- Then you won't be able to open any tabs unless you refresh your workspace.

Console error log when you try to open a new file  is down below

```
tabmanager.js:501 Uncaught Error: Called open too early. Please wait until a pane is available. Use the ready event.(…)

createTab	@tabmanager.js:501
open	@tabmanager.js:1093
(anonymous function)	@tree.js:1129
openSelection	@tree.js:1121
EventEmitter._emit.EventEmitter._dispatchEvent	@event_emitter.js:60
onClick	@default_handlers.js:190
EventEmitter._emit.EventEmitter._dispatchEvent	@event_emitter.js:66
onMouseEvent	@mouse_handler.js:67
onMouseUp	@default_handlers.js:183
EventEmitter._emit.EventEmitter._dispatchEvent	@event_emitter.js:66
onMouseEvent	@mouse_handler.js:67
onCaptureEnd	@mouse_handler.js:115
onMouseUp	@event.js:107
```

**Comment by SylannBin** [comment]
I am facing the same problem it seems, but I can't confirm the conditions that led to it.

After going back to the page, I found only the right part of the pane visible.
The left part was black, without possible interaction.
After another reloading of the page, (and cleaning the cache, etc ...) the full main window is now black and useless.
I tried to use cloud9 on Firefox after that, and the ide is in the same state.
Here is the stack trace after trying to double click a file in the left tree:

`Uncaught Error: Called open too early. Please wait until a pane is available. Use the ready event.
    at createTab (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:43250:42)
    at Plugin.open (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:43365:5)
    at https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:21250:67
    at Array.forEach (native)
    at Array.openSelection (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:21249:5)
    at Tree.EventEmitter._emit.EventEmitter._dispatchEvent (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:4236:46)
    at MouseHandler.onClick (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:5308:74)
    at Tree.EventEmitter._emit.EventEmitter._dispatchEvent (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:4236:126)
    at MouseHandler.onMouseEvent (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:5452:13)
    at MouseHandler.onMouseUp (https://static.c9.io/nc-3.1.3457-6b18f936/config/workspace-nodejs.js:5306:43)
createTab @ workspace-nodejs.js:43250
open @ workspace-nodejs.js:43365
(anonymous) @ workspace-nodejs.js:21250
openSelection @ workspace-nodejs.js:21249
EventEmitter._emit.EventEmitter._dispatchEvent @ workspace-nodejs.js:4236
onClick @ workspace-nodejs.js:5308
EventEmitter._emit.EventEmitter._dispatchEvent @ workspace-nodejs.js:4236
onMouseEvent @ workspace-nodejs.js:5452
onMouseUp @ workspace-nodejs.js:5306
EventEmitter._emit.EventEmitter._dispatchEvent @ workspace-nodejs.js:4236
onMouseEvent @ workspace-nodejs.js:5452
onCaptureEnd @ workspace-nodejs.js:5464
onMouseUp @ workspace-nodejs.js:4796
2017-02-16 14:19:19.575 `
