### ISSUE TITLE
get 500error when first install and start

### ISSUE THREAD

**Issue by nevermoreluo** [c9/core#392]
Hi,I'm just new here, 
I got this error when i run ` node server.js -p 8080 -l 0.0.0.0 -a nevermore:never -w /root/c9work`

```
Success!
run 'node server.js -p 8080 -a :' to launch Cloud9
root@never:/opt/cloud9/c9sdk# 
root@never:/opt/cloud9/c9sdk# node server.js -p 8080 -l 0.0.0.0 -a nevermore:never -w /root/c9work
Starting standalone
Connect server listening at http://xxxxxxxxx:8080
Using basic authentication
CDN: version standalone initialized /opt/cloud9/c9sdk/build
Started '/opt/cloud9/c9sdk/configs/standalone' with config 'standalone'!
Cloud9 is up and running
Error: Cannot find module '/opt/cloud9/c9sdk/plugins/c9.vfs.standalone/../../configs/ide/default.js'
    at Module._resolveFilename (module.js:326:15)
    at Function.modules._resolveFilename (/opt/cloud9/c9sdk/node_modules/c9/setup_paths.js:32:20)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at getConfig (/opt/cloud9/c9sdk/plugins/c9.vfs.standalone/standalone.js:348:12)
    at /opt/cloud9/c9sdk/plugins/c9.vfs.standalone/standalone.js:123:30
    at processNext (/opt/cloud9/c9sdk/node_modules/frontdoor/lib/section.js:205:13)
    at /opt/cloud9/c9sdk/node_modules/frontdoor/lib/section.js:209:17
    at decodeParams (/opt/cloud9/c9sdk/node_modules/frontdoor/lib/route.js:262:9)
```

----------------------

There is all cmd i have done with ubuntu 16.04.1 LTS:
```
git clone git://github.com/c9/core.git c9sdk
cd c9sdk
scripts/install-sdk.sh
node server.js -p 8080 -l 0.0.0.0 -a nevermore:never -w /root/c9work
```
did I miss anything, or how can i solve this?

**Comment by nightwing** [comment]
Thanks for reporting! https://github.com/c9/core/tree/master/configs/ide should fix this issue, please check it.
