### ISSUE TITLE
Cannot set workspace to '/'

### ISSUE THREAD

**Issue by AndlsH** [c9/core#396]
```
node /opt/c9sdk/server.js -w / -p 8080 -l 0.0.0.0 -a :
Starting standalone
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by nightwing** [comment]
looks like something else is running on 0.0.0.0:8080, try using another port, or run `net -tulpn` to find and stop the process using 8080

**Comment by AndlsH** [comment]
Forgot to stop the other one running in screen 😂 
Thanks for your reply!
