### ISSUE TITLE
Path must be a string, Received true (startup error)

### ISSUE THREAD

**Issue by LightningShock** [c9/core#448]
I'm running with git-bash on windows, hopefully to fix the long startup times with my app.
I get this error: 
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at loadSettings (E:\ShockPC Backup\lightning\c9sdk\server.js:153:14)
    at start (E:\ShockPC Backup\lightning\c9sdk\server.js:189:20)
    at E:\ShockPC Backup\lightning\c9sdk\server.js:127:13
    at E:\ShockPC Backup\lightning\c9sdk\node_modules\async\lib\async.js:122:13
    at _each (E:\ShockPC Backup\lightning\c9sdk\node_modules\async\lib\async.js:46:13)
    at Object.async.each (E:\ShockPC Backup\lightning\c9sdk\node_modules\async\lib\async.js:121:9)
    at startConfigs (E:\ShockPC Backup\lightning\c9sdk\server.js:124:15)
    at main (E:\ShockPC Backup\lightning\c9sdk\server.js:117:5)
```
The startup script I use is on my desktop, and C9 is on a external drive (E:)

**Comment by nightwing** [comment]
What startup script, and what version of ide do you use 
the stacktrace points to an empty line https://github.com/c9/core/blob/master/server.js#L153

**Comment by LightningShock** [comment]
oops, i added a console.log for debugging, it actually points to 
[Line 151](https://github.com/c9/core/blob/master/server.js#L151)
my startup code is this
```bash
cd /e/ShockPC\ Backup/lightning/c9sdk
git fetch
UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
	git pull origin master
	scripts/install-sdk.sh
	git reset --hard
elif [ $REMOTE = $BASE ]; then
    echo "Need to push"
else
    echo "Diverged"
fi
node server.js -a lightning:password -port 8080 -listen 192.168.0.4 -w ./../
read
```
here's the fixed stacktrace
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at loadSettings (E:\ShockPC Backup\lightning\c9sdk\server.js:151:14)
    at start (E:\ShockPC Backup\lightning\c9sdk\server.js:188:20)
    at E:\ShockPC Backup\lightning\c9sdk\server.js:127:13
    at E:\ShockPC Backup\lightning\c9sdk\node_modules\async\lib\async.js:122:13
    at _each (E:\ShockPC Backup\lightning\c9sdk\node_modules\async\lib\async.js:46:13)
    at Object.async.each (E:\ShockPC Backup\lightning\c9sdk\node_modules\async\lib\async.js:121:9)
    at startConfigs (E:\ShockPC Backup\lightning\c9sdk\server.js:124:15)
    at main (E:\ShockPC Backup\lightning\c9sdk\server.js:117:5)
```
I use the latest version

**Comment by nightwing** [comment]
you either need to use
```
node server.js -a lightning:password --port 8080 --listen 192.168.0.4 -w ./../
```
or
```
node server.js -a lightning:password -p 8080 -l 192.168.0.4 -w ./../
```
`-listen` is interpreted by optimist as passing multiple shorthands, somewhat like `git commit -am "x"` is interpreted as `git commit -a -m "x"`
