### ISSUE TITLE
Unable to load `pty.js`

### ISSUE THREAD

**Issue by r351574nc3** [c9/core#463]
I am trying to run C9 on a server and access through my browser. I keep running into the following:
```
Error: Dynamic loading not supported
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/c9/c9sdk/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10) '/root/.c9/node_modules/pty.js'
Error: Dynamic loading not supported
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/c9/c9sdk/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10) 'pty.js'
Error: Dynamic loading not supported
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/c9/c9sdk/node_modules/pty.nw.js/lib/pty.js:9:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10) 'pty.nw.js'
unable to initialize pty.js:
PTY is not supported.```

Why `pty.nw.js`? That sounds **NW.js** related which is not what I'm trying to use. It's loading it as part of `vfs-local`. 

This seems to be preventing me from using the terminal feature which I would really like to use.

**Comment by r351574nc3** [comment]
This happened because I was using a `--fully-static` built nodejs binary
