### ISSUE TITLE
installation error :  pty.js

### ISSUE THREAD

**Issue by yyexplore01** [c9/core#48]
An error was ment when I installed c9 core,  the pty.js can't be installed successfully

```
> pty.js@0.2.6 install /home/vagrant/cloud9/node_modules/pty.js
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.36.tar.gz local checksum deb28b6c1e92f278e3f02e2d427d3fcd996e52b06dd0e0ad3ddc5d4a6a3dcc90 not match remote b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:442:13)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/cloud9/node_modules/pty.js
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN engine simplefunc@0.0.2: wanted: {"node":">= 0.6.0 && < 0.9.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN optional dep failed, continuing pty.js@0.2.6
```

nodejs  :  v0.10.36
npm: 1.4.28
python2.7
tmux installed

**Comment by nightwing** [comment]
Looks like https://github.com/c9/install/blob/master/install.sh completed successfully and error happened only when installing node_modules
Could you try removing node_modules/pty.js if it was created and running cloud9 with `~/.c9/node/bin/node` instead of `node`?

**Comment by bradydowling** [comment]
@yyexplore01 I ran `npm install pty.js` and that fixed it for me.

**Comment by yyexplore01** [comment]
ok , my problem was fixed by installing pty.js manually, thanks !
