### ISSUE TITLE
Cloud9 launch issue

### ISSUE THREAD

**Issue by wandermonk** [c9/core#487]
After running scripts/install-sdk.sh the shell script gave the final message

Success!
run 'node server.js -p 8080 -a :' to launch Cloud9

But, when i tried starting the server.js application i am getting the below issue

pi@raspberrypi:~/.nvm/c9sdk $ node server.js -p 8080 -a :
Starting standalone
Trace: Error while starting '/home/pi/.nvm/c9sdk/configs/standalone':
    at /home/pi/.nvm/c9sdk/server.js:223:25
    at Object.createApp (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:578:16)
    at /home/pi/.nvm/c9sdk/server.js:221:29
    at resolveNext (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:74:24)
    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:100:28
    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:173:17
    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:235:32
    at LOOP (fs.js:1753:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
{ Error: Could not resolve dependencies
Missing services: app
    at checkCycles (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:411:20)
    at checkConfig (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:340:12)
    at new Architect (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:439:25)
    at Object.createApp (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:575:15)
    at /home/pi/.nvm/c9sdk/server.js:221:29
    at resolveNext (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:74:24)
    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:100:28
    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:173:17
    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:235:32
    at LOOP (fs.js:1753:14)
  unresolved: [ 'app' ],
  resolved:
   [ 'hub',
     'connect',
     'http',
     'connect.static',
     'connect.remote-address',
     'connect.render',
     'connect.render.ejs',
     'connect.redirect',
     'connect.cors',
     'connect.favicon',
     'c9.static.node',
     'error.logger',
     'analytics',
     'metrics',
     'connect.error',
     'preview.handler',
     'api',
     'passport' ] } 'Error: Could not resolve dependencies\nMissing services: app\n    at checkCycles (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:411:20)\n    at checkConfig (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:340:12)\n    at new Architect (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:439:25)\n    at Object.createApp (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:575:15)\n    at /home/pi/.nvm/c9sdk/server.js:221:29\n    at resolveNext (/home/pi/.nvm/c9sdk/node_modules/architect/architect.js:74:24)\n    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:100:28\n    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:173:17\n    at /home/pi/.nvm/c9sdk/node_modules/architect/architect.js:235:32\n    at LOOP (fs.js:1753:14)'

**Comment by nightwing** [comment]
what  does git status show? if there are some modified files in node_modules directory, try running `git reset --hard`

**Comment by glingy** [comment]
I've got the same problem and resetting didn't help.
