### ISSUE TITLE
Start c9 on port 80

### ISSUE THREAD

**Issue by abalter** [c9/core#494]
I tried the obvious:

```
$ node /var/www/html/c9sdk/server.js -w /var/www/html --port 80 --listen localhost
Starting standalone
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

```

I'd like to be able to reach c9 at `localhost`.

**Comment by das7pad** [comment]
Only the `root` user is allowed to run services on ports below 1024.

You could setup nginx with a `proxy_pass http://127.0.0.1:YOURPORT` entry in the `/` location.
_Please take a look at authentication as well: Using `-a someuser:somepassword` for the c9-startup is a good start._
