### ISSUE TITLE
Error creating TMUX session:  Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by drmrbrewer** [c9/core#531]
With a self-hosted cloud9 on Ubuntu 18.04 and Node 10.x, the IDE loads fine in general but when I try to open a terminal I get the following errors in the Chrome console in which the IDE is running:

	Error connecting to the terminal:  {stack: "8: 36: TypeError: Cannot read property 'on' of und…06:13)↵    at ChildProcess.emit (events.js:191:7)", message: "Cannot read property 'on' of undefined"}message: "Cannot read property 'on' of undefined"stack: "8: 36: TypeError: Cannot read property 'on' of undefined↵    at check (/cloud9/plugins/node_modules/vfs-local/localfs.js:1688:25)↵    at /cloud9/plugins/node_modules/vfs-local/localfs.js:1676:17↵    at resolvePath (/cloud9/plugins/node_modules/vfs-local/localfs.js:363:13)↵    at ptyspawn (/cloud9/plugins/node_modules/vfs-local/localfs.js:1667:9)↵    at run (/cloud9/plugins/node_modules/vfs-local/localfs.js:2086:17)↵    at start (/cloud9/plugins/node_modules/vfs-local/localfs.js:2058:13)↵    at /cloud9/plugins/node_modules/vfs-local/localfs.js:1972:25↵    at ChildProcess.exithandler (child_process.js:209:5)↵    at emitTwo (events.js:106:13)↵    at ChildProcess.emit (events.js:191:7)"__proto__: Object
	(anonymous) @ default.js:81524
	(anonymous) @ default.js:109183
	processCallback @ default.js:160773
	(anonymous) @ default.js:160800
	callbacks.(anonymous function) @ default.js:160121
	Agent._onMessage @ default.js:160093
	EventEmitter.emit @ default.js:756
	onMessage @ default.js:160328
	EventEmitter.emit @ default.js:756
	ReliableSocket.onMessage @ default.js:160934
	EventEmitter.emit @ default.js:756
	ReconnectSocket.onMessage @ default.js:161271
	Emitter.emit @ default.js:157980
	Socket.onPacket @ default.js:156605
	(anonymous) @ default.js:156455
	Emitter.emit @ default.js:157980
	Transport.onPacket @ default.js:156860
	Transport.onData @ default.js:156856
	ws.onmessage @ default.js:157601

	Error creating TMUX session:  Cannot read property 'on' of undefined
	(anonymous) @ default.js:81386
	(anonymous) @ default.js:81529
	(anonymous) @ default.js:109183
	processCallback @ default.js:160773
	(anonymous) @ default.js:160800
	callbacks.(anonymous function) @ default.js:160121
	Agent._onMessage @ default.js:160093
	EventEmitter.emit @ default.js:756
	onMessage @ default.js:160328
	EventEmitter.emit @ default.js:756
	ReliableSocket.onMessage @ default.js:160934
	EventEmitter.emit @ default.js:756
	ReconnectSocket.onMessage @ default.js:161271
	Emitter.emit @ default.js:157980
	Socket.onPacket @ default.js:156605
	(anonymous) @ default.js:156455
	Emitter.emit @ default.js:157980
	Transport.onPacket @ default.js:156860
	Transport.onData @ default.js:156856
	ws.onmessage @ default.js:157601

Any ideas how to resolve this?

**Comment by drmrbrewer** [comment]
@nightwing any ideas?

**Comment by drmrbrewer** [comment]
And I have tried the suggestion [here](https://github.com/c9/core/issues/197#issuecomment-154320986) but it complains that there is no `package,json` file in `~/.c9/`.

**Comment by drmrbrewer** [comment]
Now seems to be working OK... for no apparent reason.
