### ISSUE TITLE
Ubuntu installation problems alongside with Terminal plugin not installed

### ISSUE THREAD

**Issue by poliveira89** [c9/core#78]
So, through the process to attempt successfully install Cloud9 Core project, I have encountered severed problems and difficulties.

The first one it was, when I tried to install `install-sdk.sh`, this could be my fault, but for some reason I did think that this shell script it was responsible for the install of all dependencies. so I executed this command several times appearing different messages:

````
g++: command not found
````

````
git: command not found
````

````
npm: command not found
````

````
node: command not found
````

So, I decided to install those dependencies before executing this command:
````
apt-get update && sudo apt-get upgrade -y
apt-get install -y git wget curl build-essential g++ nodejs nodejs-legacy npm
```

After this I could finally execute `install-sdk.sh`, and a long installation process started: everything went well, even the part that checkouts every plugin and moving forward to the `npm install` part. 
When I got the following error on the output (without pausing or terminate in any way the installation):
````
(...)

npm ERR! Failed resolving git HEAD (git://github.com/cloud9ide/pty.js.git) fatal: ambiguous argument '10e31e23ed': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git://github.com/cloud9ide/pty.js.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git://github.com/cloud9ide/pty.js.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git://github.com/cloud9ide/pty.js.git)
npm WARN optional dep failed, continuing pty.js@git://github.com/cloud9ide/pty.js.git#10e31e23ed

(...)
````

After all the installation process went "well" returning this:
````
--------------------------------------------------------------------
Success!
run 'node server.js -p 8181 -l 0.0.0.0 -a :' to launch Cloud9
````

So, look into the "Success" message I ran that command:

````bash
$ node server.js -p 8181 -l 0.0.0.0 -a :
Connect server listening at http://10.0.2.15:8181
CDN: version standalone initialized /home/vagrant/cloud9/build
Started '/home/vagrant/cloud9/configs/standalone' with config 'standalone'!
cache /home/vagrant/cloud9/build/standalone/skin/default/dark.css
unable to initialize pty.js:
{ [Error: Cannot find module 'pty.js'] code: 'MODULE_NOT_FOUND' } { [Error: Cannot find module 'pty.nw.js'] code: 'MODULE_NOT_FOUND' }
wrapping module lib/architect/architect
wrapping module async
wrapping module smith
wrapping module vfs-socket/consumer
wrapping module engine.io
wrapping module msgpack-js

(...)
````
Note: Look that I receive a `MODULE_NOT_FOUND` message... either way...

When I opened the page on the browser, I got a dialog asking me to install "Terminal Plugin", I have selected and "Finish" the process, got an message warning that was not able to install.

So, may environment is: Ubuntu 14.10, node v0.10.25, npm v1.3.10.

**Comment by poliveira89** [comment]
I decided to look into NPM, so I did this:

````bash
$ npm list
c9@3.0.1 /home/vagrant/cloud9
├── ace@1.1.9 extraneous
├── ace_tree@0.1.0 extraneous
├── acorn@1.0.3
├── amd-loader@0.0.5
├── architect@0.1.11
├── architect-build@0.1.0 extraneous
├── async@0.9.0
├── base64id@0.1.0
├── c9@0.1.0
├─┬ connect@2.12.0
│ ├── batch@0.5.0
│ ├── buffer-crc32@0.2.1
│ ├── bytes@0.2.1
│ ├── cookie@0.1.0
│ ├── cookie-signature@1.0.1
│ ├── fresh@0.2.0
│ ├── methods@0.1.0
│ ├─┬ multiparty@2.2.0
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── stream-counter@0.2.0
│ ├── negotiator@0.3.0
│ ├── pause@0.0.1
│ ├── raw-body@1.1.2
│ └── uid2@0.0.3
├─┬ connect-architect@0.2.0 extraneous
│ ├── UNMET DEPENDENCY connect-flash ~0.1.0
│ ├── UNMET DEPENDENCY email-validator ~0.1.2
│ └── UNMET DEPENDENCY ua-parser-js ~0.7.0
├── debug@0.7.4
├── ejs@0.8.8
├── emmet@0.0.1 (git://github.com/cloud9ide/emmet-core.git#2ff6dc06ad037357fe19a52e23effeb08a8dc1d6)
├─┬ engine.io@1.5.1
│ ├─┬ debug@1.0.3
│ │ └── ms@0.6.2
│ ├─┬ engine.io-parser@1.2.1
│ │ ├── after@0.8.1
│ │ ├── arraybuffer.slice@0.0.6
│ │ ├── base64-arraybuffer@0.1.2
│ │ ├── blob@0.0.2
│ │ ├─┬ has-binary@0.1.5
│ │ │ └── isarray@0.0.1
│ │ └── utf8@2.0.0
│ └─┬ ws@0.5.0
│   ├── nan@1.4.3
│   ├── options@0.0.6
│   └── ultron@1.0.1
├─┬ engine.io-client@1.5.1
│ ├── component-emitter@1.1.2
│ ├── component-inherit@0.0.3
│ ├─┬ debug@1.0.4
│ │ └── ms@0.6.2
│ ├─┬ engine.io-parser@1.2.1
│ │ ├── after@0.8.1
│ │ ├── arraybuffer.slice@0.0.6
│ │ ├── base64-arraybuffer@0.1.2
│ │ ├── blob@0.0.2
│ │ ├─┬ has-binary@0.1.5
│ │ │ └── isarray@0.0.1
│ │ └── utf8@2.0.0
│ ├─┬ has-cors@1.0.3
│ │ └── global@2.0.1
│ ├── indexof@0.0.1
│ ├─┬ parsejson@0.0.1
│ │ └─┬ better-assert@1.0.2
│ │   └── callsite@1.0.0
│ ├─┬ parseqs@0.0.2
│ │ └─┬ better-assert@1.0.2
│ │   └── callsite@1.0.0
│ ├─┬ parseuri@0.0.4
│ │ └─┬ better-assert@1.0.2
│ │   └── callsite@1.0.0
│ └── xmlhttprequest@1.5.0
├─┬ eslint@0.11.0-alpha.0 (git://github.com/cloud9ide/eslint.git#e2d052aafd81ea0aa6d1d4fd9f88f3613e386160)
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.3
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├─┬ concat-stream@1.4.8
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── typedarray@0.0.6
│ ├─┬ debug@2.1.3
│ │ └── ms@0.7.0
│ ├── deepcopy@0.3.3
│ ├─┬ doctrine@0.6.4
│ │ ├── esutils@1.1.6
│ │ └── isarray@0.0.1
│ ├─┬ escope@1.0.3
│ │ └── estraverse@2.0.0
│ ├── esprima@1.2.5
│ ├── esprima-fb@8001.2001.0-dev-harmony-fb
│ ├── estraverse@1.9.3
│ ├── estraverse-fb@1.3.1
│ ├─┬ js-yaml@3.2.7
│ │ ├─┬ argparse@1.0.2
│ │ │ ├── lodash@3.8.0
│ │ │ └── sprintf-js@1.0.2
│ │ └── esprima@2.0.0
│ ├─┬ minimatch@1.0.0
│ │ ├── lru-cache@2.6.2
│ │ └── sigmund@1.0.0
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ ├── object-assign@1.0.0
│ ├─┬ optionator@0.4.0
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.0.6
│ │ ├── levn@0.2.5
│ │ ├── prelude-ls@1.1.1
│ │ ├── type-check@0.3.1
│ │ └── wordwrap@0.0.2
│ ├── strip-json-comments@1.0.2
│ ├── text-table@0.2.0
│ ├── user-home@1.1.1
│ └── xml-escape@1.0.0
├─┬ form-data@0.2.0
│ ├─┬ combined-stream@0.0.7
│ │ └── delayed-stream@0.0.5
│ └─┬ mime-types@2.0.10
│   └── mime-db@1.8.0
├─┬ frontdoor@0.0.1 extraneous
│ └── UNMET DEPENDENCY request ~2.12.0
├── http-error@0.0.5
├── kaefer@0.1.0 extraneous
├─┬ less@2.5.0
│ ├─┬ errno@0.1.2
│ │ └── prr@0.0.0
│ ├── graceful-fs@3.0.6
│ ├── image-size@0.3.5
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ ├─┬ promise@6.1.0
│ │ └── asap@1.0.0
│ ├─┬ request@2.55.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.4
│ │ │ └─┬ readable-stream@1.0.33
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── caseless@0.9.0
│ │ ├─┬ combined-stream@0.0.7
│ │ │ └── delayed-stream@0.0.5
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ har-validator@1.7.0
│ │ │ ├── bluebird@2.9.25
│ │ │ ├─┬ chalk@1.0.0
│ │ │ │ ├── ansi-styles@2.0.1
│ │ │ │ ├── escape-string-regexp@1.0.3
│ │ │ │ ├─┬ has-ansi@1.0.3
│ │ │ │ │ ├── ansi-regex@1.1.1
│ │ │ │ │ └── get-stdin@4.0.1
│ │ │ │ ├─┬ strip-ansi@2.0.1
│ │ │ │ │ └── ansi-regex@1.1.1
│ │ │ │ └── supports-color@1.3.1
│ │ │ ├─┬ commander@2.8.1
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ └─┬ is-my-json-valid@2.10.1
│ │ │   ├── generate-function@2.0.0
│ │ │   ├─┬ generate-object-property@1.1.1
│ │ │   │ └── is-property@1.0.2
│ │ │   ├── jsonpointer@1.1.0
│ │ │   └── xtend@4.0.0
│ │ ├─┬ hawk@2.3.1
│ │ │ ├── boom@2.7.1
│ │ │ ├── cryptiles@2.0.4
│ │ │ ├── hoek@2.12.0
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@0.10.1
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.0
│ │ ├─┬ mime-types@2.0.10
│ │ │ └── mime-db@1.8.0
│ │ ├── node-uuid@1.4.3
│ │ ├── oauth-sign@0.6.0
│ │ ├── qs@2.4.1
│ │ ├── stringstream@0.0.4
│ │ ├── tough-cookie@1.1.0
│ │ └── tunnel-agent@0.4.0
│ └─┬ source-map@0.4.2
│   └── amdefine@0.1.0
├── mime@1.2.11
├── mkdirp@0.3.5
├── msgpack-js@0.1.5
├── msgpack-js-browser@0.1.4
├─┬ nak@0.3.3
│ ├── colors@0.6.2
│ ├── isbinaryfile@2.0.0
│ └── simplefunc@0.0.2
├── netutil@0.0.2
├─┬ optimist@0.6.1
│ ├── minimist@0.0.10
│ └── wordwrap@0.0.2
├── qs@0.6.6
├─┬ read@1.0.5
│ └── mute-stream@0.0.4
├─┬ rusha@0.7.8
│ ├─┬ grunt@0.4.5
│ │ ├── async@0.1.22
│ │ ├── coffee-script@1.3.3
│ │ ├── colors@0.6.2
│ │ ├── dateformat@1.0.2-1.2.3
│ │ ├── eventemitter2@0.4.14
│ │ ├── exit@0.1.2
│ │ ├─┬ findup-sync@0.1.3
│ │ │ ├─┬ glob@3.2.11
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ └─┬ minimatch@0.3.0
│ │ │ │   ├── lru-cache@2.6.2
│ │ │ │   └── sigmund@1.0.0
│ │ │ └── lodash@2.4.2
│ │ ├── getobject@0.1.0
│ │ ├─┬ glob@3.1.21
│ │ │ ├── graceful-fs@1.2.3
│ │ │ └── inherits@1.0.0
│ │ ├─┬ grunt-legacy-log@0.1.1
│ │ │ ├── lodash@2.4.2
│ │ │ └── underscore.string@2.3.3
│ │ ├── grunt-legacy-util@0.2.0
│ │ ├── hooker@0.2.3
│ │ ├── iconv-lite@0.2.11
│ │ ├─┬ js-yaml@2.0.5
│ │ │ ├─┬ argparse@0.1.16
│ │ │ │ ├── underscore@1.7.0
│ │ │ │ └── underscore.string@2.4.0
│ │ │ └── esprima@1.0.4
│ │ ├── lodash@0.9.2
│ │ ├─┬ minimatch@0.2.14
│ │ │ ├── lru-cache@2.6.2
│ │ │ └── sigmund@1.0.0
│ │ ├─┬ nopt@1.0.10
│ │ │ └── abbrev@1.0.5
│ │ ├── rimraf@2.2.8
│ │ ├── underscore.string@2.2.1
│ │ └── which@1.0.9
│ └─┬ grunt-contrib-connect@0.8.0
│   ├─┬ connect@2.19.6
│   │ ├── basic-auth-connect@1.0.0
│   │ ├─┬ body-parser@1.3.1
│   │ │ └── raw-body@1.1.6
│   │ ├── bytes@1.0.0
│   │ ├─┬ compression@1.0.7
│   │ │ ├─┬ accepts@1.0.3
│   │ │ │ └── negotiator@0.4.6
│   │ │ ├── compressible@1.1.0
│   │ │ └── vary@0.1.0
│   │ ├─┬ connect-timeout@1.1.0
│   │ │ └── debug@0.8.1
│   │ ├── cookie@0.1.2
│   │ ├── cookie-parser@1.1.0
│   │ ├── cookie-signature@1.0.3
│   │ ├─┬ csurf@1.2.1
│   │ │ └─┬ csrf-tokens@1.0.4
│   │ │   ├── rndm@1.1.0
│   │ │   ├── scmp@0.0.3
│   │ │   └── uid2@0.0.3
│   │ ├─┬ debug@1.0.2
│   │ │ └── ms@0.6.2
│   │ ├── errorhandler@1.0.2
│   │ ├── escape-html@1.0.1
│   │ ├─┬ express-session@1.2.1
│   │ │ ├── buffer-crc32@0.2.1
│   │ │ ├── debug@0.8.1
│   │ │ ├── uid2@0.0.3
│   │ │ └── utils-merge@1.0.0
│   │ ├── fresh@0.2.2
│   │ ├─┬ method-override@2.0.2
│   │ │ ├── methods@1.0.1
│   │ │ └── vary@0.1.0
│   │ ├── morgan@1.1.1
│   │ ├─┬ multiparty@3.2.8
│   │ │ ├─┬ readable-stream@1.1.13
│   │ │ │ ├── core-util-is@1.0.1
│   │ │ │ ├── inherits@2.0.1
│   │ │ │ ├── isarray@0.0.1
│   │ │ │ └── string_decoder@0.10.31
│   │ │ └── stream-counter@0.2.0
│   │ ├── on-headers@0.0.0
│   │ ├── parseurl@1.0.1
│   │ ├── pause@0.0.1
│   │ ├── response-time@2.0.0
│   │ ├── serve-favicon@2.0.1
│   │ ├─┬ serve-index@1.1.1
│   │ │ ├─┬ accepts@1.0.3
│   │ │ │ └── negotiator@0.4.6
│   │ │ └── batch@0.5.0
│   │ ├─┬ serve-static@1.2.3
│   │ │ └─┬ send@0.4.3
│   │ │   ├─┬ finished@1.2.2
│   │ │   │ └── ee-first@1.0.3
│   │ │   └── range-parser@1.0.2
│   │ ├─┬ type-is@1.2.1
│   │ │ └── mime-types@1.0.0
│   │ └── vhost@1.0.0
│   ├── connect-livereload@0.4.1
│   ├── open@0.0.5
│   └─┬ portscanner@0.2.3
│     └── async@0.1.15
├─┬ send@0.1.4
│ ├── fresh@0.2.0
│ └── range-parser@0.0.4
├── simple-mime@0.0.8
├── smith@0.1.22
├─┬ tern@0.8.1 (git://github.com/lennartcl/tern.git#97464df789dbb4d81ca4579383a02b320c69563d)
│ ├─┬ glob@3.2.11
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.3.0
│ │   ├── lru-cache@2.6.2
│ │   └── sigmund@1.0.0
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.6.2
│ │ └── sigmund@1.0.0
│ └── typescript@1.0.1
├── tern_from_ts@0.0.1 (git://github.com/cloud9ide/tern_from_ts.git#6a0107e602b0d044fe1753533cf31f52cf5fb95a)
├── through@2.2.0
├── tmp@0.0.25
├── treehugger@0.0.2 extraneous
├─┬ uglify-js@2.4.16
│ ├── async@0.2.10
│ ├─┬ optimist@0.3.7
│ │ └── wordwrap@0.0.2
│ ├─┬ source-map@0.1.34
│ │ └── amdefine@0.1.0
│ └── uglify-to-browserify@1.0.2
├── vfs-child@0.3.0 extraneous
├── vfs-http-adapter@0.2.3 extraneous
├── vfs-lint@0.0.1 extraneous
├── vfs-local@0.3.13
├── vfs-nodefs-adapter@0.3.0 extraneous
├── vfs-socket@0.3.13
└─┬ ws@0.4.31
  ├── commander@0.6.1
  ├── nan@0.3.2
  ├── options@0.0.6
  └── tinycolor@0.0.1

npm ERR! extraneous: ace_tree@0.1.0 /home/vagrant/cloud9/node_modules/ace_tree
npm ERR! extraneous: kaefer@0.1.0 /home/vagrant/cloud9/node_modules/kaefer
npm ERR! extraneous: vfs-nodefs-adapter@0.3.0 /home/vagrant/cloud9/node_modules/vfs-nodefs-adapter
npm ERR! extraneous: ace@1.1.9 /home/vagrant/cloud9/node_modules/ace
npm ERR! extraneous: architect-build@0.1.0 /home/vagrant/cloud9/node_modules/architect-build
npm ERR! extraneous: connect-architect@0.2.0 /home/vagrant/cloud9/node_modules/connect-architect
npm ERR! missing: connect-flash@~0.1.0, required by connect-architect@0.2.0
npm ERR! missing: email-validator@~0.1.2, required by connect-architect@0.2.0
npm ERR! missing: ua-parser-js@~0.7.0, required by connect-architect@0.2.0
npm ERR! extraneous: frontdoor@0.0.1 /home/vagrant/cloud9/node_modules/frontdoor
npm ERR! missing: request@~2.12.0, required by frontdoor@0.0.1
npm ERR! extraneous: vfs-child@0.3.0 /home/vagrant/cloud9/node_modules/vfs-child
npm ERR! extraneous: treehugger@0.0.2 /home/vagrant/cloud9/node_modules/treehugger
npm ERR! extraneous: vfs-http-adapter@0.2.3 /home/vagrant/cloud9/node_modules/vfs-http-adapter
npm ERR! extraneous: vfs-lint@0.0.1 /home/vagrant/cloud9/node_modules/vfs-lint
npm ERR! not ok code 0
````

Several modules with `UNMET DEPENDENCY` flag even did not show on installation process, strange :confused:

PS: There is not sign of `pty.js` module.

**Comment by poliveira89** [comment]
And I have tried manually to install `pty.js`:

````bash
$ npm install git+https://git@github.com/cloud9ide/pty.js.git#10e31e23ed
npm WARN package.json ace_tree@0.1.0 No description
npm WARN package.json ace_tree@0.1.0 No repository field.
npm WARN package.json ace_tree@0.1.0 No README data
npm WARN package.json kaefer@0.1.0 No repository field.
npm WARN package.json kaefer@0.1.0 No README data
npm WARN package.json msgpack-js-browser@0.1.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json vfs-nodefs-adapter@0.3.0 No README data
npm WARN package.json vfs-lint@0.0.1 No README data
npm ERR! Failed resolving git HEAD (https://git@github.com/cloud9ide/pty.js.git) fatal: ambiguous argument '10e31e23ed': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (https://git@github.com/cloud9ide/pty.js.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (https://git@github.com/cloud9ide/pty.js.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (https://git@github.com/cloud9ide/pty.js.git)
npm ERR! Error: Command failed: fatal: ambiguous argument '10e31e23ed': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "git+https://git@github.com/cloud9ide/pty.js.git#10e31e23ed"
npm ERR! cwd /home/vagrant/cloud9
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/cloud9/npm-debug.log
npm ERR! not ok code 0
````

And `npm install git+https://github.com/cloud9ide/pty.js.git#10e31e23ed` as well `npm install github.com/cloud9ide/pty.js.git#10e31e23ed` equally without success.

**Comment by nightwing** [comment]
Please try again. This error should be fixed after this commit https://github.com/c9/core/commit/26ee3d7ca949887a6cbdbd7c79311e07999a1a8b
